import Head from 'next/head'
import Header from "@/component/Header/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Employee Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header></Header>
      </main>
    </>
  )
}
